Update patch set 18
Patch Set 18: Verified-1

David: First of all, really grateful for your help. Second, a question: build is working very well in standalone mode. In Gerrit tree, however, there are two issues:

 1. Tests are failing because external dependency (wiremock) is not loaded:

    bazel test plugins/sync-index:sync_index_tests.................
    ERROR: /home/ehecabo/workspace/gerrit/plugins/sync-index/BUILD:23:1: no such package '@wiremock//jar': error loading package 'external': The repository named 'wiremock' could not be resolved and referenced by '//plugins/sync-index:sync_index_tests'.
    ERROR: Analysis of target '//plugins/sync-index:sync_index_tests' failed; build aborted.
    INFO: Elapsed time: 3.512s
    ERROR: Couldn't start the build. Unable to run tests.

 2. When building the Eclipse project, wiremock is not being added to the classpath.

If I add wiremock to the list of exported dependencies in plugin api, it works. Given this library is not widely used in Gerrit, however, this does not seems like a good solution. Any other idea how to fix this? Thanks again!

Patch-set: 18
Label: Verified=-1