Update patch set 15
Patch Set 15: Verified-1

It works in standalone but in tree, it looks like there is a library not exposed:

plugins/sync-index/src/main/java/com/ericsson/gerrit/plugins/syncindex/HttpClientProvider.java:20: error: package org.apache.http does not exist
import org.apache.http.HttpResponse;
                      ^
plugins/sync-index/src/main/java/com/ericsson/gerrit/plugins/syncindex/HttpClientProvider.java:26: error: package org.apache.http.config does not exist
import org.apache.http.config.Registry;
....

This fails for buck buck and bazel, probably caused by https://gerrit-review.googlesource.com/#/c/93155/

Patch-set: 15